### ISSUE TITLE
Autojs手机安装完成为打包插件，不是运行APP，盼望回复，附件喊手机型号系统+软件信息

### ISSUE THREAD

**Issue by LLyjj** [ShyLoong/autojs-script#12]

**Comment by LLyjj** [comment]
![1](https://user-images.githubusercontent.com/93553139/139742324-637df7ae-7124-45af-9f41-0ffedca7f0e6.png)
![2](https://user-images.githubusercontent.com/93553139/139742329-ce36083d-5389-4644-83bc-51353db97623.png)

**Comment by LLyjj** [comment]
已解决

**Comment by PalmerCharles** [comment]
请问如何解决

**Comment by LLyjj** [comment]
> 请问如何解决

度娘搜索下载autojs
